from pydantic_settings import BaseSettings
from datetime import datetime

class Settings(BaseSettings):
    HOST: str = "127.0.0.1"
    PORT: int = 8000
    DEBUG: bool = False  # Keep False for security
    
    # ngrok settings
    NGROK_ENABLED: bool = False
    NGROK_SUBDOMAIN: str = ""  # Will be auto-generated by ngrok
    #et9g7Oh0rJQ60ggA
    # Security settings
    ALLOWED_HOSTS: list = ["*"]  # Allow ngrok subdomains
    CORS_ORIGINS: list = ["*"]  # Allow all origins for development
    
    # Database settings (localhost for security)
    MONGO_URI: str = ""
    DB_NAME: str = "phone_products"
    
    # Secret keys
    PRIMARY_SECRET_KEY: str = ""  # Set in .env
    SECONDARY_SECRET_KEY: str = ""
    
    # Redis settings
    REDIS_URL: str = ""
    REDIS_PASSWORD: str = ""
    
    # Email settings
    BREVO_API_KEY: str = ""
    EMAIL_FROM: str = "pricemonitor@dealsonline.ninja"
    EMAIL_FROM_NAME: str = "Phone Deals Price Monitor"
    
    # Rate limiting
    RATE_LIMITING: bool = True
    MAX_REQUESTS_PER_MINUTE: int = 60
    
    model_config = {
        "env_file": ".env",
        "env_file_encoding": "utf-8",
        "extra": "ignore"
    }

    @property
    def SECRET_KEY(self) -> str:
        return self.PRIMARY_SECRET_KEY
    
    @property
    def VALID_SECRET_KEYS(self) -> list:
        keys = [self.PRIMARY_SECRET_KEY]
        if self.SECONDARY_SECRET_KEY:
            keys.append(self.SECONDARY_SECRET_KEY)
        return keys

settings = Settings()

